version: '3.8'

services:
  api:
    build: .
    container_name: ship-coordination-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ships_db
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: ship-coordination-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ships_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
